const CARD_WIDTH = 500;
const CARD_HEIGHT = 500;
const HORIZONTAL_GAP = 50;
const VERTICAL_MARGIN_BETWEEN_TIERS = 80;
const EXTRA_OFFSET = 100;

export {
  CARD_WIDTH,
  CARD_HEIGHT,
  HORIZONTAL_GAP,
  VERTICAL_MARGIN_BETWEEN_TIERS,
  EXTRA_OFFSET,
};
